CREATE TABLE CONTACT_FORM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SUBJECT VARCHAR(1000) NOT NULL,
    MESSAGE TEXT NOT NULL,
    SUBMISSION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);